feat: Custom ArrayList 제작, 적용
Vint-zs/Anipal_Ios pull request #45
Opened 2021-12-10 14:11 UTC by ImYoungUn

- list에 데이터가 없을 경우 해당 index의 값을 읽어오기 전 if list.count > index 처리를 해야 안정적인 운영이 가능하지만, 매번 하기에는 상당한 번거로움이 있어서 해당 조건문을 내장한 ArrayList 를 제작.
 - 이제는 a = [] 하고 a[0].id을 접근하는게 아니라, a=ArrayList<Item>() 하고 a.get(0)?.id 를 하면 리스트에 item이 하나도 없을 때 생기는 array index out of range 를 방지해줄 수 있습니다!

2021-12-11 02:22 UTC, sshrik requested changes
delete 나 split(splice) 같은건 없어도 되나요?

가능하다면 Arrayist를 상속받아서 필요한것만 overriding하는건 어떨까용?

2021-12-11 02:53 UTC, ImYoungUn commented on Old/anipal 1/Model/CustomArrayList.swift
> +    }
@sshrik 
delete 나 split(splice) 같은 함수들은 그때그때 필요할때 만들거나, getList()로 일반 swift list를 가져와서 사용하면 될 것 같아서 이거 만들어놨어용

2021-12-11 03:35 UTC, sshrik commented on Old/anipal 1/Model/CustomArrayList.swift
> +    }
다른 기능들은 모두 list 랑 똑같다면 굳이 함수 하나 추가를 위해서 새로운 Type을 만들어야 할까요?_?

* 처음 코드를 읽는 사람들이 ArrayList의 기능이 뭐지? 하고 파일을 들어가서 찾아봐야 이해가 될 것 같아요!
* 동일한 다른 기능들 때문에 코딩해야 할 다른 기능들이 늘어나요! `get` 을 쉽게 쓰려고 다른 함수들을 `ArrayList.list.delete(item)` 으로 쓰는것도 이상하고, 같은 기능 wrapping을 위해서 함수 하나하나 작성해줘야하는것도 불필요한것 같아요! Compile 언어 특성상 List에서 Compile 최적화가 일어날 수도 있을지도?

`checkZeroBoundaryGet(list: Array<S>, index: Int) -> S)` 같은 함수로 만들거나 혹은 Class명을 명확하게하고, Compiler에게 이 Class는 List 확장한것이니 알아서 최적화하라~ 라고 하게 List를 Extends 하는 방법이 좋을 것 같습니다!

만약 Extends 하는 방법이라면 여전히 [] 로 indexing 하는 방법이 열려있으니, 이것을 막는 방법도 생각해야 할 것 같습니다~!

2021-12-11 03:44 UTC, ImYoungUn commented
> 가능하다면 Arrayist를 상속받아서 필요한것만 overriding하는건 어떨까용?
좋은 아이디어 감사합니당ㅎㅎ Swift Array 클래스 extension 해서 get 함수를 추가했어요!  확인 부탁드립니닷

2021-12-11 03:58 UTC, sshrik commented on Old/anipal 1/Model/CustomArrayList.swift
> +
오잉 똑같은게 2개가 있는데 무엇이죠?_? ㅋㅋㅋ

2021-12-11 03:58 UTC, sshrik approved these changes

2021-12-11 07:14 UTC, KimJoonOh approved these changes

2021-12-12 05:52 UTC, ImYoungUn commented on Old/anipal 1/Model/CustomArrayList.swift
> +
삭제 한 내역을 commit 안해땃..! 추가했어욥ㅎㅎ

2021-12-12 05:53 UTC, merged